CUDA_VISIBLE_DEVICES=0 python -m flashrag.retriever.index_builder \
  --retrieval_method bge \
  --model_path /mnt/data/you/modelscope/bge-large-en-v1.5 \
  --corpus_path /mnt/data/you/datasets/infoseek_val/wiki_100k_flatten.jsonl \
  --save_dir /mnt/data/you/data/datasets/infoseek_val/indexes/ \
  --use_fp16 \
  --max_length 512 \
  --batch_size 256 \
  --pooling_method cls \
  --faiss_type Flat \
  --index_modal image